---

- name: Ensure all security, critical, and rollup updates are installed
  win_updates:
    use_scheduled_task: yes
    state: installed
    reboot: no
    reboot_timeout: 3600
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
